[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["test-proc-macro"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-proc-macro = { path = "./test-proc-macro" }
