[package]
name = "test-proc-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
rstml = "0.11.2"
syn = { version = "2.0.38", features = ["full"] }
